echo off

echo "args[1] = %1"
echo "args[2] = %2"

echo "----------------------------------------------------------------------------------------------------------------------"
echo "This script will install LuaRocks without destroying your (maybe) already installed LuaRocks installation!"

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Backing up users config-5.1.lua and default-lua-version.lua if they exist"
if not exist %1 mkdir %1
if exist %1\config-5.1.lua move %1\config-5.1.lua %1\config-5.1.lua.bak
if exist %1\default-lua-version.lua move %1\default-lua-version.lua %1\default-lua-version.lua.bak

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Creating config-5.1.lua and default-lua-version.lua"
%2\.build\luarocks-3.9.2-windows-32\luarocks.exe config --lua-version="5.1" --local lua_dir %2\.build\LuaJIT-2.0.4

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Init LuaRocks project"
%2\.build\luarocks-3.9.2-windows-32\luarocks.exe init noita-vscode-debugger --lua-version="5.1" --output="%2\mods\noita-vscode-debugger" --homepage="https://github.com/Ismoh/noita-vscode-debugger" --license="MIT"
%2\.build\luarocks-3.9.2-windows-32\luarocks.exe config --scope project variables.LUA_DIR %2\.build\LuaJIT-2.0.4
%2\.build\luarocks-3.9.2-windows-32\luarocks.exe config --scope project variables.LUA_BINDIR %2\.build\LuaJIT-2.0.4\bin
%2\.build\luarocks-3.9.2-windows-32\luarocks.exe config --scope project variables.LUA_INCDIR %2\.build\LuaJIT-2.0.4\include
%2\.build\luarocks-3.9.2-windows-32\luarocks.exe config --scope project variables.LUA_LIBDIR %2\.build\LuaJIT-2.0.4\lib

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Small cleanup of unnecessary files generated by LuaRocks"
del %2\mods\noita-vscode-debugger\.gitignore

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Reverting users config-5.1.lua and default-lua-version.lua"
if exist %1\config-5.1.lua.bak (move %1\config-5.1.lua.bak %1\config-5.1.lua) else (del %1\config-5.1.lua)
if exist %1\default-lua-version.lua.bak (move %1\default-lua-version.lua.bak %1\default-lua-version.lua) else (del %1\default-lua-version.lua)

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Done! You can now use LuaRocks!"
